name: Continuous integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    types: [run-ci]

env:
  SLACK_WEBHOOK_URL: ${{ secrets.DEV_SLACK_WEBHOOK_URL }}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set selected color
      run: echo "Build and deploy done!"

    # Slack Notify
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: my-github
        SLACK_WEBHOOK: ${{ env.SLACK_WEBHOOK_URL }}
